
## **Cargar Excel Pandas 🐍**
Pandas es una biblioteca de Python de código abierto que se utiliza para la manipulación, el análisis y la limpieza de datos. Proporciona herramientas rápidas y flexibles para trabajar con datos tabulares, de forma similar a las hojas de cálculo o las tablas SQL.

Pandas se utiliza en ciencia de datos y análisis debido a su integración con bibliotecas como:

* NumPy : operaciones numéricas
* Matplotlib y Seaborn : visualización de datos
* SciPy : análisis estadístico
* Scikit-learn : flujos de trabajo de aprendizaje automático

In [28]:
#pip install pandas
#pip install numpy
#pip insatll openpyxl
import pandas as pd


#importar a
df = pd.read_excel('dataset_ventas.xlsx', engine='openpyxl')

#df.head()# 5 primeras filas
#df.tail()# 5 ultimas filas
#df.sample()# 5 filas aleatorias
#df.info()#informacion general sobre el  DataFrame
#df.describe()#Info sobre el DataFrame(estadistica)
#df.shape()#Numero de filas y columnas

df.shape# numero de fulas y columnas

(1000, 7)

## *Manejo de valores faltantes y duplicado*

In [29]:
#1. I dentificar valores nulos en el DateFrame
df.isnull().sum()

fecha              0
ciudad             0
categoria          0
producto           0
cantidad           0
precio_unitario    0
total_venta        0
dtype: int64

### 1.Cargar el archivo Excel

In [30]:
import pandas as pd

df = pd.read_excel('dataset_ventas.xlsx', engine='openpyxl')
df.shape
df.isnull().sum()

fecha              0
ciudad             0
categoria          0
producto           0
cantidad           0
precio_unitario    0
total_venta        0
dtype: int64

### 2.Codificar categoria

In [31]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['categoria_label'] = le.fit_transform(df['categoria'])

df[['categoria', 'categoria_label']].head()

    categoria  categoria_label
0  Tecnología                4
1   Papelería                2
2  Tecnología                4
3   Papelería                2
4   Papelería                2

In [32]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

categoria_encoded = encoder.fit_transform(df[['categoria']])

pd.DataFrame(
    categoria_encoded,
    columns=encoder.get_feature_names_out(['categoria'])
).head()

,categoria_Alimentos,categoria_Hogar,categoria_Papelería,categoria_Ropa,categoria_Tecnología
0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0

### 3.Normalización y estandarización

In [33]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Normalización
normalizador = MinMaxScaler()
df['total_venta_normalizada'] = normalizador.fit_transform(df[['total_venta']])

# Estandarización
estandarizador = StandardScaler()
df['total_venta_estandarizada'] = estandarizador.fit_transform(df[['total_venta']])

# Mostrar resultados
df[['total_venta', 'total_venta_normalizada', 'total_venta_estandarizada']].head()

   total_venta  total_venta_normalizada  total_venta_estandarizada
0       484104                 0.098539                  -0.775878
1      2139476                 0.439075                   0.702276
2      1075800                 0.220260                  -0.247526
3      2015532                 0.413577                   0.591601
4       200916                 0.040283                  -1.028749

### 4.SMOTE

In [34]:
from imblearn.over_sampling import SMOTE

# Separar características y variable objetivo
X = df[['cantidad', 'precio_unitario', 'total_venta']]
y = df['categoria_label']

# Aplicar SMOTE
smote = SMOTE(random_state=42)
X_balanceado, y_balanceado = smote.fit_resample(X, y)

# Comprobar el balance
print("Antes:")
print(y.value_counts())

print("\nDespués:")
print(y_balanceado.value_counts())

Antes:
categoria_label
1    209
0    209
3    202
2    195
4    185
Name: count, dtype: int64

Después:
categoria_label
4    209
2    209
3    209
1    209
0    209
Name: count, dtype: int64

In [35]:
# Crear el conjunto de datos final
df_final = X_balanceado.copy()

# Agregar la variable objetivo
df_final['categoria'] = y_balanceado

# Mostrar las primeras filas
df_final.head()

   cantidad  precio_unitario  total_venta  categoria
0         8            60513       484104          4
1        19           112604      2139476          2
2         8           134475      1075800          4
3        18           111974      2015532          2
4         1           200916       200916          2